import { ReactElement } from 'react';
import Head from 'next/head';
import { NextPageWithLayout } from './_app';
import { Container, Text } from '@chakra-ui/react';
import { useRouter } from 'next/router';
import { Layout } from '@/components/layouts/Layout';

const Piece: NextPageWithLayout = () => {
    const router = useRouter();
    
    console.log('router.query.slug -', router.query.slug);

    return (
    <>
      <Head>
        <title>Piece</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Container maxW={'4xl'} padding={0}>
        <Text>Piece Page</Text>
      </Container>
    </>
  )
}

Piece.getLayout = function getLayout(page: ReactElement) {
  return (
    <Layout>
      {page}
    </Layout>
  )
}

export default Piece;
