import { ReactElement, useEffect } from 'react';
import Head from 'next/head';
import { NextPageWithLayout } from './_app';
import { Layout } from '@/components/layouts/Layout';
import { UserLayout } from '@/components/layouts/UserLayout';
import { useUserSession } from '@/hooks/useUserSession';
import { useUser } from '@/context/AuthContext';
import { useUpdateUserSession } from '@/hooks/useUpdateUserSession';

const Home: NextPageWithLayout = () => {
    // useUpdateUserSession();
    // const { session, setSession } = useUser();

    // useEffect(() => {
    //   setSession(session);
    // }, [session, setSession]);

    return (
    <>
      <Head>
        <title>Home</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <p>Home</p>
    </>
  )
}

Home.getLayout = function getLayout(page: ReactElement) {
  return (
    <UserLayout>
      {page}
    </UserLayout>
  )
}

export default Home;
