import { ReactElement } from 'react';
import Head from 'next/head';
import { NextPageWithLayout } from './_app';
import { Layout } from '@/components/layouts/Layout';
import { UserLayout } from '@/components/layouts/UserLayout';

const Home: NextPageWithLayout = () => {

    return (
    <>
      <Head>
        <title>Home</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <p>Home</p>
    </>
  )
}

Home.getLayout = function getLayout(page: ReactElement) {
  return (// TODO - Create the UserLayout and use it here
    <UserLayout>
      {page}
    </UserLayout>
  )
}

export default Home;
