import { ReactElement, useEffect } from 'react';
import Head from 'next/head';
import { NextPageWithLayout } from './_app';
import { UserLayout } from '@/components/layouts/UserLayout';
import { Button, Link } from '@chakra-ui/react';
import { useRouter } from 'next/router';

const Home: NextPageWithLayout = () => {
    const router = useRouter();

    return (
    <>
      <Head>
        <title>Home</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Button onClick={() => router.push('/submissions')}>Submissions</Button>
    </>
  )
}

Home.getLayout = function getLayout(page: ReactElement) {
  return (
    <UserLayout>
      {page}
    </UserLayout>
  )
}

export default Home;
