import { ReactElement } from 'react';
import Head from 'next/head';
import { ChakraProvider } from "@chakra-ui/react";
import { NextPageWithLayout } from './_app';
import { Layout } from '@/components/layouts/Layout';

const Home: NextPageWithLayout = () => {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <p>Hello</p>
    </>
  )
}

Home.getLayout = function getLayout(page: ReactElement) {
  return (
    <ChakraProvider>
      <Layout>
        {page}
      </Layout>
    </ChakraProvider>
  )
}

export default Home;
