import { ReactElement } from 'react'
import Head from 'next/head'
import { NextPageWithLayout } from './_app'
import { Layout } from '@/components/layouts/Layout'
import { NeverStopLearning } from '@/components/NeverStopLearning/NeverStopLearning'
import { RecentlyPublished } from '@/components/RecentlyPublished/RecentlyPublished'
import { LinkCard } from '@/components/LinkCard/LinkCard'
import { WeeklyDigest } from '@/components/WeeklyDigest/WeeklyDigest'
import {
  Box, 
  Heading, 
  SimpleGrid, 
  Stack, 
  Text, 
  Divider,
} from '@chakra-ui/react'

/* ## Component Details
• General
  • Make sure everything is aligned, i.e. make the first component conform to everything
• Never Stop Learning Component
  • When a user enters in a search query and presses the search button, this should cause Search component to open and execute the search query.
• Note, Essay, and Contributor Cards
  • Clicking on their “Browse —>” button should direct the user to the associated pages 
*/

const Landing: NextPageWithLayout = () => <>
  <Head>
    <title>Home</title>
    <meta name="description" content="Generated by create next app" />
    <meta name="viewport" content="width=device-width, initial-scale=1" />
    <link rel="icon" href="/favicon.ico" />
  </Head>
  <Stack spacing='16'>
    <NeverStopLearning/>
    <Divider/>
    <Box>
      <Heading marginBottom='16px'>What is a Digital Garden?</Heading>
      <Text>
      A digital garden is a collection of ideas, opinions, and notes that evolve over time. Like Wikipedia, you will be able to link to other pieces that are a part of the digital garden.
      </Text>
    </Box>
    <Divider/> 
     {/* The Notes, Essay, and Contributor Card Components (LinkCard) */}
    <SimpleGrid columns={3} spacing={4}>
      <LinkCard headerText='Notes' footerText='Browse ➔' footerLink='notes' 
      descriptionText='A collection of atomic notes, i.e. a single idea or a single object of attention.'
      imageSrc='https://wallpapers.com/images/high/bank-page-student-notebook-caz8w7ly9ojyj9dg.webp' />
      <LinkCard headerText='Essays' footerText='Browse ➔' footerLink='essays' 
      descriptionText='A collection of long-form narratives and opinion pieces.'
      imageSrc='https://www.qinprinting.com/blog/wp-content/uploads/2022/08/Stunning-photo-and-text-book.jpg'/>
      <LinkCard headerText='Contributors' footerText='Browse ➔' footerLink='contributors' 
      descriptionText='The wonderful individuals who have contributed their ideas to our digital garden.'
      imageSrc='/images/co-x3-graphic.png'/>
    </SimpleGrid>
    <Divider/>
    <RecentlyPublished/>
    <Divider/>
    <WeeklyDigest/>
  </Stack>
</>

Landing.getLayout = function getLayout(page: ReactElement) {
  return <Layout>{page}</Layout>
}
  
export default Landing