import { ReactElement } from 'react';
import Head from 'next/head';
import { NextPageWithLayout } from './_app';
import { Layout } from '@/components/layouts/Layout';
import { 
  Card, 
  CardHeader, 
  CardBody, 
  CardFooter, 
  Center, 
  Heading, 
  SimpleGrid, 
  Stack, 
  Text, 
  Image,
  Box,
  // useMediaQuery, 
} from '@chakra-ui/react';

const Landing: NextPageWithLayout = () => {
// const [isMobile] = useMediaQuery("(max-width: 768px)");

return <>
  <Head>
    <title>Home</title>
    <meta name="description" content="Generated by create next app" />
    <meta name="viewport" content="width=device-width, initial-scale=1" />
    <link rel="icon" href="/favicon.ico" />
  </Head>
  <Stack spacing='16'>
      <Card size='sm' 
        bg='#111' 
        align='left' 
        padding={8} 
        borderRadius={20} 
        color='white'
        direction={{base: 'column', sm: 'row'}}>
        <Stack>
          <CardHeader>
            <Heading>Never Stop Learning<br/>and Never Stop Sharing</Heading>
          </CardHeader>
          <CardBody>
            <Text>This is our digital garden, where we are publishing single and multi-author pieces of knowledge and sharing them with the world.</Text>
          </CardBody>          
        </Stack>
        <Box borderRadius={100}>
          <Image objectFit='cover' alt='Image'
            maxW={{base: '100%', sm: '200px'}}         
            src='https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSVpaDka6f73wv23c7_QcIGSTWQ8YGagIJSdZ8hGJntVe3IqObG'>
          </Image>
        </Box>
      </Card>
      <Card variant='unstyled'>
        <CardHeader>
          <Heading>What is a Digital Garden?</Heading>
        </CardHeader>
        <CardBody>
          <Text>
          A digital garden is a collection of ideas, opinions, and notes that evolve over time. Like Wikipedia, you will be able to link to other pieces that are a part of the digital garden.
          </Text>
        </CardBody>
      </Card>
    
      <SimpleGrid columns={3} spacing={4}>
        <Card>
          <CardHeader>
            <Heading size='md'>Notes</Heading>
          </CardHeader>
          <CardFooter>Browse →</CardFooter>
        </Card>
        <Card>
          <CardHeader>
            <Heading size='md'>Essays</Heading>
          </CardHeader>
          <CardFooter>Browse →</CardFooter>
        </Card>
        <Card>
          <CardHeader>
            <Heading size='md'>Contributors</Heading>
          </CardHeader>
          <CardFooter>Browse →</CardFooter>
        </Card>
      </SimpleGrid>
    <Center>Recently Published</Center>
    <Center>Weekly Digest is Coming Soon!</Center>
  </Stack>
</>}
Landing.getLayout = function getLayout(page: ReactElement) {
    return (
      <Layout>
        {page}
      </Layout>
    )
  }
  
  export default Landing;
