import { PageHeader } from "@/components/PageHeader/PageHeader";
import { ReactElement, useEffect, useState } from "react";
import { NextPageWithLayout } from "./_app";
import { Layout } from "@/components/layouts/Layout";
import Head from "next/head";
import { useFetchNotes } from "@/hooks/useFetchNotes";
import { PieceCard } from "@/components/PieceCard/PieceCard";

const Notes: NextPageWithLayout = () => {
  const { published_piece_view } = useFetchNotes();
  console.log(published_piece_view);

  return (
    <>
      <Head>
        <title>Home</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <PageHeader title={"some header"} subtitle={"some subtitle header"} />

      {published_piece_view &&
        published_piece_view?.map((p) => {
          <PieceCard
            key={p.id}
            piece={{
              title: p.title,
              growth_stage: p.growth_stage,
              cover_url: p.cover_url,
            }}
            contributor={{ full_name: "Sam Smith" }}
          ></PieceCard>;
        })}
    </>
  );
};

Notes.getLayout = function getLayout(page: ReactElement) {
  return <Layout>{page}</Layout>;
};

export default Notes;
