import { PageHeader } from "@/components/PageHeader/PageHeader";
import { ReactElement, useEffect, useState } from "react";
import { NextPageWithLayout } from "./_app";
import { Layout } from "@/components/layouts/Layout";
import Head from "next/head";
import { useFetchNotes } from "@/hooks/useFetchNotes";
import { PieceCard } from "@/components/PieceCard/PieceCard";

const Notes: NextPageWithLayout = () => {
  const { notes } = useFetchNotes();
  console.log(notes);

  return (
    <>
      <Head>
        <title>Home</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <PageHeader
        title={"Notes"}
        subtitle={
          "A collection of atomic notes, i.e. a single idea or a single object of attention."
        }
      />

      {notes &&
        notes?.map((n) => {
          <PieceCard
            piece={n}
            contributor={{
              id: "1",
              avatar_url: "",
              bio: "I like Coding",
              username: "TheeSamSmith01",
              full_name: "Sam Smith",
              created_at: "",
              updated_at: "",
            }}
          ></PieceCard>;
        })}
    </>
  );
};

Notes.getLayout = function getLayout(page: ReactElement) {
  return <Layout>{page}</Layout>;
};

export default Notes;
