import React, { ReactElement } from 'react';
import Head from 'next/head';
import { NextPageWithLayout } from './_app';
import { Layout } from '@/components/layouts/Layout';
import {
  Button,
  FormControl,
  Flex,
  Heading,
  Input,
  Stack,
  Text,
  useColorModeValue,
} from '@chakra-ui/react';
import { useForm } from 'react-hook-form';
import { useRouter } from 'next/router';
import { supabaseClient } from './api/auth';

type ForgotPasswordFormInputs = {
  email: string;
};

const ResetPassword: NextPageWithLayout = () => {
  const {
    register,
    handleSubmit
  } = useForm<ForgotPasswordFormInputs>();
  const [error, setError] = React.useState<string | null>(null);
  const router = useRouter();

  const onSubmit = async (data: any) => {
    console.log('onSubmit');
    setError(null);
    try {
      const response = await supabaseClient.auth.resetPasswordForEmail(data.email, {
        redirectTo: 'http://localhost:3000/update-password',
      });
      if (response?.error?.message) {
        setError(response.error.message);
      }
    } catch(error: any) {
      setError(error.message);
    }
  }

    return (
    <>
      <Head>
        <title>Request Password Reset</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Flex
      minH={'60vh'}
      align={'center'}
      justify={'center'}>
        <Stack
          spacing={4}
          w={'full'}
          maxW={'md'}
          bg={useColorModeValue('white', 'gray.700')}
          rounded={'xl'}
          boxShadow={'lg'}
          p={6}
          my={12}>
          <Heading lineHeight={1.1} fontSize={{ base: '2xl', md: '3xl' }}>
            Forgot your password?
          </Heading>
          <Text
            fontSize={{ base: 'sm', sm: 'md' }}
            color={useColorModeValue('gray.800', 'gray.400')}>
            You&apos;ll get an email with a reset link
          </Text>
          <form onSubmit={handleSubmit(onSubmit)}>
            <FormControl id="email">
              <Input
                placeholder="your-email@example.com"
                _placeholder={{ color: 'gray.500' }}
                type="email"
                id="email"
                {...register('email')}
              />
            </FormControl>
            <Stack spacing={6}>
              {error && <p>{error}</p>}
              <Button
                type="submit"
                bg={'blue.400'}
                color={'white'}
                _hover={{
                  bg: 'blue.500',
                }}>
                Request Reset
              </Button>
            </Stack>
          </form>
        </Stack>
      </Flex>
    </>
  )
}

ResetPassword.getLayout = function getLayout(page: ReactElement) {
  return (
    <Layout>
      {page}
    </Layout>
  )
}

export default ResetPassword;