

export const essays = [
        {
            content: "Hello", 
            cover_url: "https://user-images.githubusercontent.com/2876874/200214400-563fc519-679a-4f3c-b7b8-85586a7f1606.png", 
            created_at: null,
            description: null,
            growth_stage: "Seedling",
            id: "1",
            title: "Blah 1",
            type: "Essay",
            updated_at: null,
            url_key: "blah-one"
        },
        {
            content: "Hello", 
            cover_url: "https://user-images.githubusercontent.com/2876874/200214400-563fc519-679a-4f3c-b7b8-85586a7f1606.png", 
            created_at: null,
            description: null,
            growth_stage: "Seedling",
            id: "2",
            title: "Blah 2",
            type: "Essay",
            updated_at: null,
            url_key: "blah-one"
        },
        {
            content: "Hello", 
            cover_url: "https://user-images.githubusercontent.com/2876874/200214400-563fc519-679a-4f3c-b7b8-85586a7f1606.png", 
            created_at: null,
            description: null,
            growth_stage: "Seedling",
            id: "3",
            title: "Blah 3",
            type: "Essay",
            updated_at: null,
            url_key: "blah-one"
        },
        {
            content: "Hello", 
            cover_url: "https://user-images.githubusercontent.com/2876874/200214400-563fc519-679a-4f3c-b7b8-85586a7f1606.png", 
            created_at: null,
            description: null,
            growth_stage: "Seedling",
            id: "4",
            title: "Blah 4",
            type: "Essay",
            updated_at: null,
            url_key: "blah-one"
        },
        {
            content: "Hello", 
            cover_url: "https://user-images.githubusercontent.com/2876874/200214400-563fc519-679a-4f3c-b7b8-85586a7f1606.png", 
            created_at: null,
            description: null,
            growth_stage: "Seedling",
            id: "5",
            title: "Blah 5",
            type: "Essay",
            updated_at: null,
            url_key: "blah-one"
        },
        {
            content: "Hello", 
            cover_url: "https://user-images.githubusercontent.com/2876874/200214400-563fc519-679a-4f3c-b7b8-85586a7f1606.png", 
            created_at: null,
            description: null,
            growth_stage: "Seedling",
            id: "6",
            title: "Blah 6",
            type: "Essay",
            updated_at: null,
            url_key: "blah-one"
        },
        {
            content: "Hello", 
            cover_url: "https://user-images.githubusercontent.com/2876874/200214400-563fc519-679a-4f3c-b7b8-85586a7f1606.png", 
            created_at: null,
            description: null,
            growth_stage: "Seedling",
            id: "7",
            title: "Blah 7",
            type: "Essay",
            updated_at: null,
            url_key: "blah-one"
        },
        {
            content: "Hello", 
            cover_url: "https://user-images.githubusercontent.com/2876874/200214400-563fc519-679a-4f3c-b7b8-85586a7f1606.png", 
            created_at: null,
            description: null,
            growth_stage: "Seedling",
            id: "8",
            title: "Blah 8",
            type: "Essay",
            updated_at: null,
            url_key: "blah-one"
        },
        {
            content: "Hello", 
            cover_url: "https://user-images.githubusercontent.com/2876874/200214400-563fc519-679a-4f3c-b7b8-85586a7f1606.png", 
            created_at: null,
            description: null,
            growth_stage: "Seedling",
            id: "9",
            title: "Blah 9",
            type: "Essay",
            updated_at: null,
            url_key: "blah-one"
        },
        {
            content: "Hello", 
            cover_url: "https://user-images.githubusercontent.com/2876874/200214400-563fc519-679a-4f3c-b7b8-85586a7f1606.png", 
            created_at: null,
            description: null,
            growth_stage: "Seedling",
            id: "10",
            title: "Blah 10",
            type: "Essay",
            updated_at: null,
            url_key: "blah-one"
        },
        {
            content: "Hello", 
            cover_url: "https://user-images.githubusercontent.com/2876874/200214400-563fc519-679a-4f3c-b7b8-85586a7f1606.png", 
            created_at: null,
            description: null,
            growth_stage: "Seedling",
            id: "11",
            title: "Blah 11",
            type: "Essay",
            updated_at: null,
            url_key: "blah-one"
        },
];