import { ReactElement, useEffect } from 'react';
import Head from 'next/head';
import { NextPageWithLayout } from '../_app';
import { UserLayout } from '@/components/layouts/UserLayout';
import { useFetchSubmissions } from '@/hooks/useFetchSubmissions';
import { Table, TableContainer, Tbody, Td, Th, Thead, Tr } from '@chakra-ui/react';

const Submissions: NextPageWithLayout = () => {

    const { submissions } = useFetchSubmissions();

    return (
    <>
      <Head>
        <title>Home</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <p>Submissions</p>
      <TableContainer minW={'4xl'}>
            <Table variant='striped' colorScheme='teal'>
                <Thead>
                <Tr>
                    <Th>Title</Th>
                    {/* <Th>Author</Th> */}
                    {/* <Th>Submitted</Th> */}
                </Tr>
                </Thead>
                <Tbody>
                { submissions && submissions.map((s, index) =>
                    <Tr key={s.id} cursor={'pointer'} /*onClick={() => navigate(`/submissions/${s.id}`)}*/>
                        <Td>Submission { index }</Td>
                        {/* <Td>{ s.changeDetails.author ? s.changeDetails.author : "Not Found" }</Td> */}
                        {/* <Td>{ timeTag(s.createdAt) }</Td> */}
                    </Tr>
                ) }
                </Tbody>
            </Table>
        </TableContainer>
    </>
  )
}

Submissions.getLayout = function getLayout(page: ReactElement) {
  return (
    <UserLayout>
      {page}
    </UserLayout>
  )
}

export default Submissions;
