import { ReactElement, useEffect, useState } from 'react';
import Head from 'next/head';
import { NextPageWithLayout } from '../_app';
import { UserLayout } from '@/components/layouts/UserLayout';
import { useFetchSubmissions } from '@/hooks/useFetchSubmissions';
import { Button, Flex, Spacer, Table, TableContainer, Tbody, Td, Text, Th, Thead, Tr } from '@chakra-ui/react';

type TCommentSelections = number[];

const Submissions: NextPageWithLayout = () => {
    const [commentSelections, setCommentSelections] = useState<TCommentSelections>([]);

    const { deleteSubmission, submissions } = useFetchSubmissions();

    const handleCommentSelection = (id: number): void => {
        let comments: TCommentSelections = [];

        if (commentSelections.includes(id)) {
            comments = commentSelections.filter((commentId) => commentId !== id);
        } else {
            comments = [...commentSelections, id];
        }

        setCommentSelections(comments);
    };

    const handleDeleteSubmissions = (): void => {
        if (commentSelections.length) {
            commentSelections.forEach((comment) => {
                deleteSubmission(comment);
            });

            setCommentSelections([]);
        }
    };

    return (
    <>
      <Head>
        <title>Home</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <p>Submissions</p>
      <TableContainer minW={'4xl'}>
            <Table variant='striped' colorScheme='teal'>
                <Thead>
                <Tr>
                    <Th>
                        <Flex align="center">
                            <Text fontSize="md" textTransform="none">New Comments</Text>

                            <Spacer />

                            <Text fontSize="sm" fontWeight="normal" textTransform="none" mr={6}>{commentSelections.length} Selected</Text>

                            <Button
                                disabled={commentSelections.length === 0}
                                onClick={handleDeleteSubmissions}>
                                    Delete
                            </Button>
                        </Flex>
                    </Th>
                    {/* <Th>Title</Th> */}
                    {/* <Th>Author</Th> */}
                    {/* <Th>Submitted</Th> */}
                </Tr>
                </Thead>
                <Tbody>
                { submissions && submissions.map((s, index) =>
                    <Tr key={s.id} cursor={'pointer'} /*onClick={() => navigate(`/submissions/${s.id}`)}*/ onClick={() => handleCommentSelection(s.id)}>
                        <Td>Submission index of { index } with id of { s.id }</Td>
                        {/* <Td>Submission { index }</Td> */}
                        {/* <Td>{ s.changeDetails.author ? s.changeDetails.author : "Not Found" }</Td> */}
                        {/* <Td>{ timeTag(s.createdAt) }</Td> */}
                    </Tr>
                ) }
                </Tbody>
            </Table>
        </TableContainer>
    </>
  )
}

Submissions.getLayout = function getLayout(page: ReactElement) {
  return (
    <UserLayout>
      {page}
    </UserLayout>
  )
}

export default Submissions;
