import { ReactElement, useEffect } from 'react';
import Head from 'next/head';
import { NextPageWithLayout } from '../_app';
import { ModeratorLayout } from '@/components/layouts/ModeratorLayout';
import { useFetchSubmissions } from '@/hooks/useFetchSubmissions';
import { Box, Table, TableContainer, Tbody, Td, Th, Thead, Tr } from '@chakra-ui/react';
import { isChangeDetails } from '@/types/utilities';
import { format } from 'date-fns';
import { useRouter } from 'next/router';

const Submissions: NextPageWithLayout = () => {
    const router = useRouter();
    const { submissions } = useFetchSubmissions();

    return (
    <>
      <Head>
        <title>Home</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <TableContainer width={'100%'}>
        <Box overflowX={'auto'}>
            <Table variant='striped' colorScheme='teal'>
                <Thead>
                <Tr>
                    <Th>Title</Th>
                    <Th>Author</Th>
                    <Th>Submitted</Th>
                </Tr>
                </Thead>
                <Tbody>
                { submissions && submissions.map((s, index) =>
                    <Tr key={s.id} cursor={'pointer'} onClick={() => router.push(`/submissions/${encodeURIComponent(s.id)}`)}>
                        { isChangeDetails(s.change_details) ?
                            <>
                                <Td>{ s.change_details.metadata.title }</Td>
                                <Td>{ s.change_details.contributor.full_name }</Td>
                            </>
                            :
                            <>
                                <Td>Submission { index }</Td>
                                <Td>Not Found</Td>
                            </>
                        }
                        <Td>{ format(new Date(s.created_at), "yyyy-MM-dd h:mm") }</Td>
                    </Tr>
                ) }
                </Tbody>
            </Table>
        </Box>
    </TableContainer>
    </>
  )
}

Submissions.getLayout = function getLayout(page: ReactElement) {
  return (
    <ModeratorLayout>
      {page}
    </ModeratorLayout>
  )
}

export default Submissions;
